### ISSUE TITLE
mute command does not fricking work

### ISSUE THREAD

**Issue by jaigitrep159** [GanerCodes/videoEditBot#20]
Command: py -3 editor.py "mt,bndc" jbp.mp4
Error:
Args: mute=1.0,bandicam=1.0
Silent_run error:
 ['sox', 'C:\\Users\\user\\Documents\\videoEditBot/active/jbp/0_jbp.wav', 'C:\\Users\\user\\Documents\\videoEditBot/active/jbp/FINAL_AUD0_jbp.wav', 'gain', '-1000']
Traceback (most recent call last):
  File "C:\Users\user\Documents\videoEditBot\subprocessHelper.py", line 16, in silent_run
    return check_call(command, stdout = DEVNULL, stderr = STDOUT, **kawrgs)
  File "C:\Python39\lib\subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python39\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Error! Args were: mute=1.0,bandicam=1.0
Traceback (most recent call last):
  File "C:\Users\user\Documents\videoEditBot\editor.py", line 1086, in videoEdit
    newExt = edit(f"{newPath}/{newFileName}", group, par, newExt = newExt, groupNumber = i, SHOWTIMER = SHOWTIMER, HIDE_FFMPEG_OUT = HIDE_FFMPEG_OUT, HIDE_ALL_FFMPEG = HIDE_ALL_FFMPEG, disallowTimecodeBreak = disallowTimecodeBreak, parentPath = parentPath, fixPrint = fixPrint, **kwargs)
  File "C:\Users\user\Documents\videoEditBot\editor.py", line 831, in edit
    TMP.run()
  File "C:\Python39\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

Editor ran into an error.

see?

**Comment by jaigitrep159** [comment]
and also i have sox v14

**Comment by jaigitrep159** [comment]
but the bot version of mute command does not work

**Comment by jaigitrep159** [comment]
and yeah i will close this now
