### ISSUE TITLE
Trying to self-host, errors on startup preventing launch

### ISSUE THREAD

**Issue by AgitationSkeleton** [GanerCodes/videoEditBot#60]
I have all the dependencies, but when I run discordBot.py I get the following errors:

Traceback (most recent call last):
  File "C:\Users\Max\Downloads\temp\videoEditBot-dev\videoEditBot-dev\discordBot.py", line 8, in <module>
    from editor.download import download
  File "C:\Users\Max\Downloads\temp\videoEditBot-dev\videoEditBot-dev\editor\__init__.py", line 6, in <module>
    from videoEditor import videoEdit as editor
  File "C:\Users\Max\Downloads\temp\videoEditBot-dev\videoEditBot-dev\editor\videoEditor.py", line 20, in <module>
    from AutotuneBot      import autotuneURL
ImportError: cannot import name 'autotuneURL' from 'AutotuneBot' (unknown location)

**Comment by sinogrime** [comment]
I recommend cloning [this](https://github.com/GanerCodes/AutotuneBot/tree/7e89391872271158d0d512158f99e5c1cf139d91) into the AutotuneBot folder.

**Comment by AgitationSkeleton** [comment]
That worked! Thank you
