### ISSUE TITLE
mute=true results in An unknown error has occured, and music= command does nothing.

### ISSUE THREAD

**Issue by AgitationSkeleton** [GanerCodes/videoEditBot#61]
`Args: mute=1.0,music=eqljbu2k0ey
music error. [WinError 2] The system cannot find the file specified
loud_run error:
 ['sox', 'C:\\Users\\Max\\Documents\\videoEditBot-dev\\videoEditBot-dev\\active/YGxuqINoXg_1104150393568632932_41816/0_1104150393568632932_41816.wav', 'C:\\Users\\Max\\Documents\\videoEditBot-dev\\videoEditBot-dev\\active/YGxuqINoXg_1104150393568632932_41816/FINAL_AUD0_1104150393568632932_41816.wav', 'gain', '-1000']
Traceback (most recent call last):
  File "C:\Users\Max\Documents\videoEditBot-dev\videoEditBot-dev\editor\subprocessHelper.py", line 24, in loud_run
    return check_call(command, **kawrgs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Max\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
`

**Comment by GanerCodes** [comment]
install sox
